name: app_v4
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.17
  geoflutterfire: 
    git:
      url: https://github.com/snappyjs/GeoFlutterFire
      ref: master
  fluster: ^1.1.2
  sliding_up_panel: ^1.0.2
  flutter_google_places: ^0.2.5
  
  cupertino_icons: ^0.1.3
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  flutter_spinkit: ^4.1.2+1
  location: ^3.0.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.0
  provider: ^4.1.2
  flutter_statusbarcolor: ^0.2.3
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0
  cloud_firestore: ^0.13.7
  email_validator: ^1.0.4
  image_picker: ^0.6.7
  image_cropper: ^1.2.2
  firebase_storage: ^3.1.6
  string_validator: ^0.1.4
  flutter_facebook_login: ^3.0.0
  pull_to_refresh: ^1.5.8
  date_range_picker: ^1.0.6
  numberpicker: ^1.2.0
  tuple: ^1.0.3
  flutter_typeahead: ^1.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

flutter:
  uses-material-design: true
  assets:
    - assets/auth_logos/
    - assets/app_logos/
    - assets/map_style/
    - assets/stock/
    - assets/default_icons/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: Ubuntu2
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf